# fly.toml app configuration file generated for latex-boi on 2025-11-26T10:00:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'latex-boi'
primary_region = 'sin'

[build]

# [http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ['app']

[[vm]]
cpu_kind = "shared"
cpus = 2
memory = "1gb"
memory_mb = 1_024

[processes]
app = "python script.py"